Feature/cleanup endpoints
the-deep/deep-extension pull request #10
Opened 2022-01-20 08:20 UTC by tnagorra

2022-01-20 18:37 UTC, priyesh777 approved these changes

2022-01-21 05:01 UTC, AdityaKhatri requested changes

2022-01-21 05:01 UTC, AdityaKhatri commented on app/Base/context/ServerContext.ts
> +// FIXME: rename this file to ServerContext
remove this

2022-01-21 05:01 UTC, AdityaKhatri commented on app/views/SourceForm/index.tsx
>          return productionValues.identifier;
wrong assignment

2022-01-21 05:17 UTC, samshara approved these changes

2022-01-21 06:00 UTC, tnagorra commented on app/views/SourceForm/index.tsx
>          return productionValues.identifier;
Oh no!

2022-01-31 09:23 UTC, AdityaKhatri approved these changes

2022-01-31 10:57 UTC, priyesh777 approved these changes

2022-04-18 01:39 UTC, priyesh777 approved these changes

2022-05-10 06:40 UTC, merged